on: pull_request
name: PR
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    CLIENT-setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: "npm"
                  cache-dependency-path: client/package-lock.json

            - name: npm i
              working-directory: client
              run: npm ci

            - name: cache deps
              uses: actions/cache/save@v4
              with:
                  path: client/node_modules
                  key: client-${{ runner.os }}-${{ hashFiles('client/package-lock.json') }}
                  restore-keys: client-${{ runner.os }}-

    CLIENT-checks:
        needs: CLIENT-setup
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                check: ["build:ci", "format:ci", "lint:ci", "test"]
        steps:
            - uses: actions/checkout@v4
            - name: Restore deps
              uses: actions/cache/restore@v4
              with:
                  path: client/node_modules
                  key: client-${{ runner.os }}-${{ hashFiles('client/package-lock.json') }}

            - name: Use Node.js 22.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x

            - name: Run ${{ matrix.check }}
              working-directory: client
              run: npm run ${{ matrix.check }}

    SERVER:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: black
              uses: psf/black@stable
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff
            - name: ruff
              working-directory: server
              run: |
                  ruff check src
